#!/usr/bin/env python

import rospy
from action_runtime import action_runtime

def main():
    rospy.init_node('action_runtime')
    action_runtime.ActionRuntime()
    rospy.spin()

if __name__ == '__main__':
    main()
